export const quotes = [
  { text: "If you don't take risks, you can't create a future!", author: "Monkey D. Ruffy — One Piece" },
  { text: "Power isn't determined by your size, but by the size of your dreams.", author: "Monkey D. Ruffy — One Piece" },
  { text: "When do people die? When they are forgotten.", author: "Dr. Hiluluk — One Piece" },
  { text: "A man's dream will never die!", author: "One Piece" },
  { text: "Forgetting is like a wound. It may heal, but it leaves a scar.", author: "Monkey D. Ruffy — One Piece" },
  { text: "Go beyond! Plus Ultra!", author: "All Might — My Hero Academia" },
  { text: "A lesson without pain is meaningless.", author: "Edward Elric — Fullmetal Alchemist" },
  { text: "Hard work betrays none, but dreams betray many.", author: "Hachiman — Oregairu" },
  { text: "If you don't like your destiny, don't accept it.", author: "Naruto Uzumaki — Naruto" },
  { text: "Human strength lies in the ability to change yourself.", author: "Saitama — One Punch Man" },
  { text: "I'll leave tomorrow's problems to tomorrow's me.", author: "Saitama — One Punch Man" },
  { text: "Fear is not evil. It tells you what your weakness is.", author: "Gildarts — Fairy Tail" },
  { text: "Push through the pain. Giving up hurts more.", author: "Vegeta — Dragon Ball Z" },
  { text: "It's not about whether you can. You do it because you want to.", author: "Erza Scarlet — Fairy Tail" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe? Nein — Mello, Death Note" },
  { text: "Whatever happens, don't regret the path you chose.", author: "Kenshin — Rurouni Kenshin" },
  { text: "If you can do something, then do it to perfection.", author: "Tsunade — Naruto" },
  { text: "Even the mightiest warriors experience fear. True courage is acting despite it.", author: "Piccolo — Dragon Ball Z" },
  { text: "Strength comes in response to a need, not a desire.", author: "Goku — Dragon Ball Z" },
  { text: "You should enjoy the little detours. That's where you find the important things.", author: "Ging — Hunter x Hunter" },
  { text: "Being weak is nothing to be ashamed of. Staying weak is.", author: "Fuegoleon — Black Clover" },
  { text: "My magic is never giving up!", author: "Asta — Black Clover" },
  { text: "It's okay not to be okay, as long as you don't give up.", author: "Karen — Anohana" },
  { text: "If you keep moving forward, you'll get stronger.", author: "Tanjiro — Demon Slayer" },
  { text: "No matter how deep the night, it always turns to day.", author: "Brook — One Piece" },
  { text: "I don't want to conquer anything. The one with the most freedom is King!", author: "Monkey D. Ruffy — One Piece" },
  { text: "Only those who suffer the journey reach the treasure.", author: "Grand Line Sprichwort" },
  { text: "Don't think. Train.", author: "Dojo-Weisheit" },
  { text: "Heroes are made by the path they choose, not the powers they have.", author: "Iron... äh, Anime-Weisheit" },
  { text: "Your playing small does not serve the crew.", author: "Kapitäns-Weisheit" },
  { text: "Today's training is tomorrow's victory.", author: "Shonen-Regel #1" },
  { text: "A real warrior trains even when no one is watching.", author: "Shonen-Regel #7" },
  { text: "Talent is given. Greatness is earned, one rep at a time.", author: "Shonen-Regel #12" },
  { text: "The hero of this story doesn't skip leg day.", author: "Shonen-Regel #23" },
  { text: "Drink your water. Even Saiyans hydrate.", author: "Shonen-Regel #42" },
  { text: "Your future self is your final boss. Train accordingly.", author: "Shonen-Regel #99" },
  { text: "Believe in the you that believes in yourself!", author: "Kamina — Gurren Lagann" },
  { text: "Don't believe in yourself. Believe in me, who believes in you!", author: "Kamina — Gurren Lagann" },
  { text: "Your drill is the drill that will pierce the heavens!", author: "Gurren Lagann" },
  { text: "Whether a fish lives in a clear stream or a ditch, as long as it keeps swimming forward, it will grow up beautifully.", author: "Koro-sensei — Assassination Classroom" },
  { text: "An excellent leader is someone who can lead even in the worst conditions.", author: "Erwin Smith — Attack on Titan" },
  { text: "If you win, you live. You have to fight.", author: "Mikasa — Attack on Titan" },
  { text: "Giving up is what kills people.", author: "Alucard — Hellsing" },
  { text: "The world is not beautiful, therefore it is.", author: "Kino's Journey" },
  { text: "Simplicity is the easiest path to true beauty.", author: "Seishuu — Barakamon" },
  { text: "Whatever you do, enjoy it to the fullest. That is the secret of life.", author: "Rider — Fate/Zero" },
  { text: "Life is not a game of luck. If you wanna win, work hard.", author: "Sora — No Game No Life" },
  { text: "We each need to find our own inspiration. Sometimes it's not easy.", author: "Kiki's Delivery Service" },
  { text: "It's more important to master the cards you're holding than to complain about ones your opponent was dealt.", author: "Grimsley — Pokémon" },
  { text: "One step at a time. One punch at a time. One round at a time.", author: "Rocky? Nein — Ippo, Hajime no Ippo" },
]
